2018-10-08 11:34:04,484 dataprocess.py [line:62] d:\python\homework3\0303\数据处理\log\wcy.log ERROR no user wcy exist
2018-10-08 11:34:05,945 dataprocess.py [line:66] d:\python\homework3\0303\数据处理\log\wcy.log INFO wcy register as USER successfully, auto exit
2018-10-08 11:34:24,517 dataprocess.py [line:56] d:\python\homework3\0303\数据处理\log\wcy.log INFO login successfully
